dist: xenial
language: r
# see also https://docs.travis-ci.com/user/languages/r

# Using the package cache to store R package dependencies can significantly
# speed up build times and is recommended for most builds.
cache:
  - apt
  - packages
sudo: required
warnings_are_errors: false
services:
- docker
install:
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt-get update
- sudo apt-get install -y python3.6 curl unixodbc-dev
- curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
- sudo pip install pipenv
- git clone https://github.com/exasol/integration-test-docker-environment.git
- Rscript -e 'install.packages("testthat")'
r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - marcelboldt/DBI 		# development version needed for DBItest
  - marcelboldt/DBItest
before_script:
  - bash -x ./integration-test-docker-environment/start-test-env.sh --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666
script:
  - cd tests && R -f testthat.R
after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'devtools::install(); lintr::lint_package()'

