language: r
warnings_are_errors: false
sudo: required

cache: apt

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get install unixodbc-dev
  - openssl aes-256-cbc -K $encrypted_38a684a4bcac_key -iv $encrypted_38a684a4bcac_iv -in exaodbc.sh.enc -out exaodbc.sh -d
  - chmod +777 exaodbc.sh
  - ./exaodbc.sh

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - rstats-db/DBI 		# development version needed for DBItest
  - rstats-db/DBItest

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'lintr::lint_package()'
