// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// exaWsConnect
Rcpp::List exaWsConnect(const std::string& host, int port, bool useTls, const std::string& username, const std::string& password, int protocolVersion);
RcppExport SEXP _exasol_exaWsConnect(SEXP hostSEXP, SEXP portSEXP, SEXP useTlsSEXP, SEXP usernameSEXP, SEXP passwordSEXP, SEXP protocolVersionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type host(hostSEXP);
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    Rcpp::traits::input_parameter< bool >::type useTls(useTlsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< int >::type protocolVersion(protocolVersionSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsConnect(host, port, useTls, username, password, protocolVersion));
    return rcpp_result_gen;
END_RCPP
}
// exaWsExecute
Rcpp::List exaWsExecute(SEXP connPtr, const std::string& sql);
RcppExport SEXP _exasol_exaWsExecute(SEXP connPtrSEXP, SEXP sqlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sql(sqlSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsExecute(connPtr, sql));
    return rcpp_result_gen;
END_RCPP
}
// exaWsFetch
std::string exaWsFetch(SEXP connPtr, int resultSetHandle, int startPosition, int numBytes);
RcppExport SEXP _exasol_exaWsFetch(SEXP connPtrSEXP, SEXP resultSetHandleSEXP, SEXP startPositionSEXP, SEXP numBytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    Rcpp::traits::input_parameter< int >::type resultSetHandle(resultSetHandleSEXP);
    Rcpp::traits::input_parameter< int >::type startPosition(startPositionSEXP);
    Rcpp::traits::input_parameter< int >::type numBytes(numBytesSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsFetch(connPtr, resultSetHandle, startPosition, numBytes));
    return rcpp_result_gen;
END_RCPP
}
// exaWsCloseResultSet
bool exaWsCloseResultSet(SEXP connPtr, int resultSetHandle);
RcppExport SEXP _exasol_exaWsCloseResultSet(SEXP connPtrSEXP, SEXP resultSetHandleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    Rcpp::traits::input_parameter< int >::type resultSetHandle(resultSetHandleSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsCloseResultSet(connPtr, resultSetHandle));
    return rcpp_result_gen;
END_RCPP
}
// exaWsDisconnect
bool exaWsDisconnect(SEXP connPtr);
RcppExport SEXP _exasol_exaWsDisconnect(SEXP connPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsDisconnect(connPtr));
    return rcpp_result_gen;
END_RCPP
}
// exaWsSetAttributes
bool exaWsSetAttributes(SEXP connPtr, const std::string& attrJson);
RcppExport SEXP _exasol_exaWsSetAttributes(SEXP connPtrSEXP, SEXP attrJsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type attrJson(attrJsonSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsSetAttributes(connPtr, attrJson));
    return rcpp_result_gen;
END_RCPP
}
// exaWsGetAttributes
std::string exaWsGetAttributes(SEXP connPtr);
RcppExport SEXP _exasol_exaWsGetAttributes(SEXP connPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsGetAttributes(connPtr));
    return rcpp_result_gen;
END_RCPP
}
// exaWsIsConnected
bool exaWsIsConnected(SEXP connPtr);
RcppExport SEXP _exasol_exaWsIsConnected(SEXP connPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type connPtr(connPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(exaWsIsConnected(connPtr));
    return rcpp_result_gen;
END_RCPP
}
// asyncRODBCIOStart
int asyncRODBCIOStart(const std::string& host, int port, const std::string& protocol);
RcppExport SEXP _exasol_asyncRODBCIOStart(SEXP hostSEXP, SEXP portSEXP, SEXP protocolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type host(hostSEXP);
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type protocol(protocolSEXP);
    rcpp_result_gen = Rcpp::wrap(asyncRODBCIOStart(host, port, protocol));
    return rcpp_result_gen;
END_RCPP
}
// asyncRODBCProxyHost
SEXP asyncRODBCProxyHost();
RcppExport SEXP _exasol_asyncRODBCProxyHost() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(asyncRODBCProxyHost());
    return rcpp_result_gen;
END_RCPP
}
// asyncRODBCProxyPort
SEXP asyncRODBCProxyPort();
RcppExport SEXP _exasol_asyncRODBCProxyPort() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(asyncRODBCProxyPort());
    return rcpp_result_gen;
END_RCPP
}
// asyncRODBCQueryStart
SEXP asyncRODBCQueryStart(SEXP chan, const std::string& query, const std::string& protocol, int writer);
RcppExport SEXP _exasol_asyncRODBCQueryStart(SEXP chanSEXP, SEXP querySEXP, SEXP protocolSEXP, SEXP writerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type chan(chanSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type query(querySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type protocol(protocolSEXP);
    Rcpp::traits::input_parameter< int >::type writer(writerSEXP);
    rcpp_result_gen = Rcpp::wrap(asyncRODBCQueryStart(chan, query, protocol, writer));
    return rcpp_result_gen;
END_RCPP
}
// asyncRODBCQueryFinish
int asyncRODBCQueryFinish(int checkWasDone);
RcppExport SEXP _exasol_asyncRODBCQueryFinish(SEXP checkWasDoneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type checkWasDone(checkWasDoneSEXP);
    rcpp_result_gen = Rcpp::wrap(asyncRODBCQueryFinish(checkWasDone));
    return rcpp_result_gen;
END_RCPP
}
// asyncEnableTracing
int asyncEnableTracing(const std::string& tracefile);
RcppExport SEXP _exasol_asyncEnableTracing(SEXP tracefileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type tracefile(tracefileSEXP);
    rcpp_result_gen = Rcpp::wrap(asyncEnableTracing(tracefile));
    return rcpp_result_gen;
END_RCPP
}
