# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exaWsConnect <- function(host, port, useTls, username, password, protocolVersion, sslCertificate = "") {
    .Call(`_exasol_exaWsConnect`, host, port, useTls, username, password, protocolVersion, sslCertificate)
}

exaWsExecute <- function(connPtr, sql) {
    .Call(`_exasol_exaWsExecute`, connPtr, sql)
}

exaWsFetch <- function(connPtr, resultSetHandle, startPosition, numBytes) {
    .Call(`_exasol_exaWsFetch`, connPtr, resultSetHandle, startPosition, numBytes)
}

exaWsCloseResultSet <- function(connPtr, resultSetHandle) {
    .Call(`_exasol_exaWsCloseResultSet`, connPtr, resultSetHandle)
}

exaWsDisconnect <- function(connPtr) {
    .Call(`_exasol_exaWsDisconnect`, connPtr)
}

exaWsSetAttributes <- function(connPtr, attrJson) {
    .Call(`_exasol_exaWsSetAttributes`, connPtr, attrJson)
}

exaWsGetAttributes <- function(connPtr) {
    .Call(`_exasol_exaWsGetAttributes`, connPtr)
}

exaWsIsConnected <- function(connPtr) {
    .Call(`_exasol_exaWsIsConnected`, connPtr)
}

asyncWSIOStart <- function(host, port, protocol) {
    .Call(`_exasol_asyncWSIOStart`, host, port, protocol)
}

asyncWSProxyHost <- function() {
    .Call(`_exasol_asyncWSProxyHost`)
}

asyncWSProxyPort <- function() {
    .Call(`_exasol_asyncWSProxyPort`)
}

asyncWSQueryStart <- function(chan, query, protocol, writer) {
    .Call(`_exasol_asyncWSQueryStart`, chan, query, protocol, writer)
}

asyncWSQueryFinish <- function(checkWasDone) {
    .Call(`_exasol_asyncWSQueryFinish`, checkWasDone)
}

asyncEnableTracing <- function(tracefile) {
    .Call(`_exasol_asyncEnableTracing`, tracefile)
}

