# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exaWsConnect <- function(host, port, useTls, username, password, protocolVersion) {
    .Call(`_exasol_exaWsConnect`, host, port, useTls, username, password, protocolVersion)
}

exaWsExecute <- function(connPtr, sql) {
    .Call(`_exasol_exaWsExecute`, connPtr, sql)
}

exaWsFetch <- function(connPtr, resultSetHandle, startPosition, numBytes) {
    .Call(`_exasol_exaWsFetch`, connPtr, resultSetHandle, startPosition, numBytes)
}

exaWsCloseResultSet <- function(connPtr, resultSetHandle) {
    .Call(`_exasol_exaWsCloseResultSet`, connPtr, resultSetHandle)
}

exaWsDisconnect <- function(connPtr) {
    .Call(`_exasol_exaWsDisconnect`, connPtr)
}

exaWsSetAttributes <- function(connPtr, attrJson) {
    .Call(`_exasol_exaWsSetAttributes`, connPtr, attrJson)
}

exaWsGetAttributes <- function(connPtr) {
    .Call(`_exasol_exaWsGetAttributes`, connPtr)
}

exaWsIsConnected <- function(connPtr) {
    .Call(`_exasol_exaWsIsConnected`, connPtr)
}

asyncRODBCIOStart <- function(host, port, protocol) {
    .Call(`_exasol_asyncRODBCIOStart`, host, port, protocol)
}

asyncRODBCProxyHost <- function() {
    .Call(`_exasol_asyncRODBCProxyHost`)
}

asyncRODBCProxyPort <- function() {
    .Call(`_exasol_asyncRODBCProxyPort`)
}

asyncRODBCQueryStart <- function(chan, query, protocol, writer) {
    .Call(`_exasol_asyncRODBCQueryStart`, chan, query, protocol, writer)
}

asyncRODBCQueryFinish <- function(checkWasDone) {
    .Call(`_exasol_asyncRODBCQueryFinish`, checkWasDone)
}

asyncEnableTracing <- function(tracefile) {
    .Call(`_exasol_asyncEnableTracing`, tracefile)
}

