name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:
  build-binaries:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release', output_path: '\bin\windows'}
          - { os: macOS-latest, r: 'release', output_path: '/bin/macosx' }
          - { os: ubuntu-latest, r: 'release', output_path: '/bin/ubuntu' }
    environment: ci_build
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install openssl MacOsX
        if: matrix.config.os == 'macOS-latest'
        run: |
          brew install openssl
          BREW_PREFIX=`brew --prefix`
      - name: Install Ubuntu package dependencies
        if: matrix.config.os == 'ubuntu-latest'
        run: |
            sudo apt-get -y update && \
               sudo apt-get -y install --no-install-recommends libcurl4-openssl-dev curl libxml2-dev  libssl-dev && \
               sudo locale-gen en_US.UTF-8 && \
               sudo update-locale LC_ALL=en_US.UTF-8 && \
               sudo apt-get -y clean && \
               sudo apt-get -y autoremove
      - name: Query dependencies
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools", dependencies=TRUE)
          devtools::install_deps()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Create output dir
        run: |
            out_put_dir="${{ runner.temp }}${{matrix.config.output_path}}"
            mkdir -p "${out_put_dir}"
            echo "output_dir=${out_put_dir}" >> $GITHUB_ENV
        shell: bash
      - name: Build
        run: |
          devtools::build(binary=TRUE, path='${{ env.output_dir }}')
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Check result
        run: |
          echo 'Target folder is ${{ env.output_dir }}'
          ls '${{ env.output_dir }}'
        shell: bash
#      - name: Upload assets to the GitHub release draft
#        uses: shogo82148/actions-upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.inputs.upload_url }}
#          asset_path: ${{ runner.temp }}/bin/${{matrix.config.os}}/*
  build-source:
    runs-on: ubuntu-latest
    environment: ci_build
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: Install package dependencies
        run: |
          sudo apt-get -y update && \
             sudo apt-get -y install --no-install-recommends libcurl4-openssl-dev curl libxml2-dev  libssl-dev && \
             sudo locale-gen en_US.UTF-8 && \
             sudo update-locale LC_ALL=en_US.UTF-8 && \
             sudo apt-get -y clean && \
             sudo apt-get -y autoremove
      - name: Query r-dependencies
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools", dependencies=TRUE)
          devtools::install_deps()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Create output dir
        run: |
          out_put_dir="${{ runner.temp }}/bin/source"
          mkdir -p "${out_put_dir}"
          echo "output_dir=${out_put_dir}" >> $GITHUB_ENV
      - name: Build
        run: |
          devtools::build(binary=FALSE, path="${{ env.output_dir }}")
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Check result
        run: |
           echo "Target folder is ${{ env.output_dir }}"
           ls "${{ env.output_dir }}"
#      - name: Upload assets to the GitHub release draft
#        uses: shogo82148/actions-upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.inputs.upload_url }}
#          asset_path: ${{ runner.temp }}/bin/source/*