name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:
  build-binaries:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }
          - { os: ubuntu-latest, r: 'release' }
    environment: ci_build
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install openssl MacOsX
        if: matrix.config.os == 'macOS-latest'
        run: |
          brew install openssl
          BREW_PREFIX=`brew --prefix`
      - name: Query dependencies
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools")
          devtools::install_deps()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Create output dir
        id: step_one
        run: |
            out_put_dir="${{ runner.temp }}/bin/${{matrix.config.os}}'
            mkdir -p "${out_put_dir}"
            echo "output_dir=${out_put_dir}" >> $GITHUB_ENV
      - name: Build
        run: |
          devtools::build(binary=TRUE, path='${{ env.output_dir }}')
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Check result
        run: |
          echo 'Target folder is ${{ env.output_dir }}'
          ls '${{ env.output_dir }}'

#      - name: Upload assets to the GitHub release draft
#        uses: shogo82148/actions-upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.inputs.upload_url }}
#          asset_path: ${{ runner.temp }}/bin/${{matrix.config.os}}/*
  build-source:
    runs-on: ubuntu-latest
    environment: ci_build
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: Query dependencies
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools")
          devtools::install_deps()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Create output dir
        id: step_one
        run: |
          out_put_dir="${{ runner.temp }}/bin/source'
          mkdir -p "${out_put_dir}"
          echo "output_dir=${out_put_dir}" >> $GITHUB_ENV
      - name: Build
        run: |
          devtools::build(binary=FALSE, path="${{ env.output_dir }}")
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Check result
        run: |
           echo "Target folder is ${{ env.output_dir }}"
           ls "${{ env.output_dir }}"
#      - name: Upload assets to the GitHub release draft
#        uses: shogo82148/actions-upload-release-asset@v1
#        with:
#          upload_url: ${{ github.event.inputs.upload_url }}
#          asset_path: ${{ runner.temp }}/bin/source/*