name: CI-BuildOnly

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: Build for ${{ matrix.config.os }}, r=${{ matrix.config.r }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' , r_tools: "42"}
          - { os: macOS-latest, r: 'release' , r_tools: "42"}
    environment: ci_build
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.r_tools }}

      - name: Show dir of C:\
        if: matrix.config.os == 'windows-latest'
        run: dir c:\
      - name: Show include folder of RTools
        if: matrix.config.os == 'windows-latest'
        run: tree "c:\rtools42\x86_64-w64-mingw32.static.posix\include" /f
      - name: Install openssl MacOsX
        if: matrix.config.os == 'macOS-latest'
        run: |
          brew install openssl
          BREW_PREFIX=`brew --prefix`
      - name: Query dependencies
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools")
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Build
        run: |
          devtools::install()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
