name: CI

on: [push, pull_request]

jobs:
   integration_tests:
    needs: prep-testbed
    environment: publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout test environment
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..
      - name: Spawn EXASOL environemnt
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666 --db-mem-size 4GB
        working-directory: ../integration-test-docker-environment
        shell: bash
