name: CI-Windows

on: [push, pull_request]

jobs:
  prep-testbed:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages("testthat")
          install.packages("devtools", dependencies = TRUE)
          install.packages("remotes")
          library(remotes);install_version("RODBC","1.3-16")
          devtools::install_github("jimhester/covr")
          devtools::install_github("jimhester/lintr")
          devtools::install_github("marcelboldt/DBI")
          devtools::install_github("marcelboldt/DBItest")
      -name: Build
        run: |
          devtools::install()