name: CI-BuildOnly

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: Build for ${{ matrix.config.os }}, r=${{ matrix.config.r }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' , r_tools: "44"}
          - { os: macos-latest-large, r: 'release' , r_tools: "44"} #MacOs Intel
          - { os: macos-latest, r: 'release' , r_tools: "44"} #MacOs Arm64
          - { os: windows-latest, r: '4.3.0' , r_tools: "43"}
          - { os: macos-latest-large, r: '4.3.0' , r_tools: "43"} #MacOs Intel
          - { os: macos-latest, r: '4.3.0', r_tools: "43"} #MacOs Arm64
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.r_tools }}

      - name: Install openssl MacOsX
        if: contains(matrix.config.os, 'macos-latest')
        run: |
          brew install unixodbc
          BREW_PREFIX=`brew --prefix`
      - name: Query dependencies (macOS)
        if: contains(matrix.config.os, 'macos-latest')
        run: |
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools")
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Query dependencies (windows)
        if: matrix.config.os == 'windows-latest'
        run: |
          options(pkgType = "win.binary")
          install.packages("RODBC")
          install.packages("DBI")
          install.packages("devtools")
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          devtools::install()
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
