name: CI-BuildOnly

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }
    environment: ci_build
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Query dependencies
        run: |
          install.packages("testthat")
          install.packages("devtools", dependencies = TRUE)
          install.packages("remotes")
          library(remotes);install_version("RODBC","1.3-16")
          devtools::install_github("jimhester/covr")
          devtools::install_github("jimhester/lintr")
          devtools::install_github("marcelboldt/DBI")
          devtools::install_github("marcelboldt/DBItest")
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
      - name: Build
        run: |
          devtools::install()
        shell: Rscript {0}
        env: # Set individual GH PAT
          GITHUB_PAT: ${{ secrets.PAT_FOR_DEVTOOLS }}
