name: CI-Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: install.packages("testthat")
        shell: Rscript {0}
      - name: Build
        run: |
          devtools::install()
        shell: Rscript {0}